package petclinic:event-store-world@0.1.0;

world event-store {
    export petclinic:store/event-store@0.1.0;

    import wasi:keyvalue/store@0.2.0-draft;
    import wasi:keyvalue/atomics@0.2.0-draft;
    import wasmcloud:messaging/consumer@0.2.0;
    import wasi:logging/logging@0.1.0-draft;
}
