package petclinic:vet-aggregate-world@0.1.0;

world vet-aggregate {
    export petclinic:vet-aggregate/vet-aggregate@0.1.0;

    import wasi:logging/logging@0.1.0-draft;
    import wasi:clocks/wall-clock@0.2.2;
}
